version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Hello
          command: |
            echo 'Hello, World!'
  on_pull_request_opened:
    docker:
      - image: circleci/ruby:2.4.2
    working_directory: ~/repo
    steps:
      - run:
          name: Hello via lambda
          command: |
            echo 'Hello, World via Lambda!!'
